# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 73d0a0c1f4e72837bf1f5f2d76d0ea8bbc92827978e584fa1a95c08b033fe8a863abcdcc890720c3faf8fd7517d3b4025a9cee7b55cbccc1cb58f1c372bc1d9f

test:
  secret_key_base: ec918dca99cc69118daa3267502ee4c455f999962d1c3cab02fc9e80755445e7b4c9512a1111cc0d5d837806dda4765e2207cd42a6c222ed1be3b29c403e9f82

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
